# Generated by Django 2.2 on 2019-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190705_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='state',
            field=models.BooleanField(default=True, verbose_name='状态，1禁用 0正常'),
        ),
    ]
