# Generated by Django 2.2 on 2019-07-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190705_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='login_ip',
            field=models.CharField(default='127.0.0.1', max_length=15, verbose_name='ipv4地址'),
        ),
    ]
