# Generated by Django 2.2 on 2019-07-09 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=30, unique=True, verbose_name='账号')),
                ('nickname', models.CharField(default='', max_length=45, verbose_name='昵称')),
                ('email', models.CharField(default='', max_length=45, unique=True, verbose_name='邮箱')),
                ('mobile', models.CharField(default='', max_length=11, unique=True, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=32, verbose_name='密码')),
                ('login_num', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后一次登录时间')),
                ('login_ip', models.CharField(max_length=15, verbose_name='ipv4地址')),
                ('state', models.BooleanField(default=True, verbose_name='状态，1禁用 0正常')),
            ],
            options={
                'verbose_name': '管理员表',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('tags', models.CharField(default='', max_length=50, verbose_name='标签')),
                ('describles', models.CharField(max_length=200, verbose_name='描述')),
                ('pic', models.CharField(default='', max_length=200, verbose_name='图片')),
                ('flag', manager.models.CustomeTinyIntField(default=0, max_length=1, verbose_name='文章推荐 0默认 1置顶 2 推荐')),
                ('add_time', manager.models.CustomeTimeStampField(default='2019-07-09 20:01:13', verbose_name='添加时间')),
                ('click', models.PositiveIntegerField(default=0, verbose_name='点击量')),
                ('support', models.PositiveIntegerField(default=0, verbose_name='点赞')),
                ('seo_title', models.CharField(max_length=50, verbose_name='seo标题')),
                ('seo_keyword', models.CharField(max_length=60, verbose_name='seo关键词')),
                ('seo_description', models.CharField(max_length=200, verbose_name='seo描述')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Admin', verbose_name='添加人')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(default='', max_length=25, verbose_name='栏目名称')),
                ('describles', models.CharField(default='', max_length=200, verbose_name='栏目描述')),
                ('pic', models.ImageField(default='', max_length=150, upload_to='uploads/%Y%m%d/', verbose_name='栏目图片')),
                ('is_menu', models.BooleanField(default=True, verbose_name='是否在首页栏目中展示')),
                ('weight', models.PositiveSmallIntegerField(default=0, verbose_name='控制栏目排序')),
                ('seo_title', models.CharField(max_length=50, verbose_name='seo标题')),
                ('seo_keyword', models.CharField(max_length=60, verbose_name='seo关键词')),
                ('seo_description', models.CharField(max_length=200, verbose_name='seo描述')),
                ('num', models.PositiveIntegerField(default=0, verbose_name='发布文章数')),
            ],
        ),
        migrations.CreateModel(
            name='Atricle_additional',
            fields=[
                ('article', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Article')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Category', verbose_name='栏目id'),
        ),
        migrations.CreateModel(
            name='Admin_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, verbose_name='操作类型')),
                ('title', models.CharField(max_length=150, verbose_name='操作日志标题')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('user_agent', models.CharField(max_length=240, verbose_name='记录用户客户端信息')),
                ('referer', models.CharField(max_length=100, verbose_name='操作来源页')),
                ('ip', models.CharField(max_length=15, verbose_name='ip')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manager.Admin', verbose_name='管理员模型的外键')),
            ],
        ),
    ]
